<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<title>VoetbalOog</title>
	<link rel="shortcut icon" href="<?php echo Zend_Registry::get("baseurl"); ?>public/images/favicon.ico" type="image/x-icon">

	<?php echo $this->metatags; ?>

	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap-theme.css">

	<?php echo $this->cssincludes; ?>
	<?php echo $this->layout()->extracssincludes; ?>

	<?php echo $this->jsincludes; ?>
	<?php echo $this->layout()->extrajsincludes; ?>

	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '<?php echo $this->googleanalyticsid; ?>']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

	</script>
</head>
<body>
<?php
	$sAppId = null;
	if( APPLICATION_ENV === "production")
	{
		$cfgFacebook = new Zend_Config_Ini( APPLICATION_PATH . '/configs/config.ini', 'facebook');
		$sAppId = $cfgFacebook->appid;
	}
?>
<?php if( strlen( $sAppId ) > 0 ): ?>
	<div id="fb-root"></div>

	<script>
		window.fbAsyncInit = function() {
			// init the FB JS SDK
			FB.init({
				appId	  : '<?php echo $sAppId; ?>', // App ID from the App Dashboard
				// channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File for x-domain communication
				channelUrl : '<?php echo Zend_Registry::get("baseurl"); ?>channel.php', // Channel File for x-domain communication
				status	 : true, // check the login status upon init?
				cookie	 : true, // set sessions cookies to allow your server to access the session?
				xfbml	  : true  // parse XFBML tags on this page?
			});
			// Additional initialization code such as adding Event Listeners goes here
		};

		(function(d, debug){
			var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
			if (d.getElementById(id)) {return;}
			js = d.createElement('script'); js.id = id; js.async = true;
			js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
			ref.parentNode.insertBefore(js, ref);
		}(document, /*debug*/ false));
	</script>
<?php endif ?>

<?php if( $this->oUser !== null ): ?>
	<script>
		function extendMySession() {
			$.ajax({
				  url: '<?php echo $this->urlcontroller; ?>/extendsession/',
				})/*.done(function() {
				  console.log( new Date() );
				})*/;

			setTimeout ( "extendMySession()", 600000 );
		}
		setTimeout ( "extendMySession()", 600000 ); // 600000 = 10 minuten
	</script>
<?php endif ?>

	<div id="container">
		<div id="hd">
			<div id="hd_left">
				<div id="hd_left_top">
				</div>
				<div id="hd_left_bottom">
					<?php echo $this->menubar; ?>
				</div>
			</div>
			<div id="hd_right">
				<?php echo $this->userinfo; ?>
			</div>
			<div style='clear:both;'></div>
		</div>

		<div id="content">
			<?php echo $this->layout()->content ?>
		</div>
		<div id="ft">
			<?php echo $this->footer ?>
		</div>
	</div>
	<?php if ( APPLICATION_ENV == 'development' ) { echo "<div id=\"debug\">".Zend_Registry::get("debug")."</div>"; } ?>
</body>
</html>