name: CI + CD

permissions:
      id-token: write
      contents: read

on:
  push:
    branches: []
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_BASENAME: "sub-${{ vars.AZURE_SUBSCRIPTION }}"
  AZURE_RESOURCEGROUP: ${{ vars.AZURE_RESOURCEGROUP }}  
  AZURE_WEBAPP_BASENAME: webapp-voetbaloog
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/voetbaloog/browser'
  NODE_VERSION: '20.x'

jobs:
  AzureDeployInfraDev:
    name: Azure Infra Deploy to Dev 
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: "github-voetbaloog-dev"
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}            
    - name: Bicep Deploy
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        subscriptionId: "${{ env.AZURE_SUBSCRIPTION_BASENAME }}-dev"
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP }}
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json environment=dev
        failOnStdErr: true
    - name: logout
      run: |
        az logout 

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present              
      #npm run test --if-present           
    - name: Zip artifact for deployment
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: zip release.zip ./* -r
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/release.zip

  AzureDeployWebAppDev:
    runs-on: ubuntu-latest
    needs: [AzureDeployInfraDev,Build]
    environment:
      name: github-voetbaloog-dev
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ env.AZURE_WEBAPP_BASENAME }}-dev"
          slot-name: 'github-voetbaloog-dev'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    