name: azure deployment

on:
  workflow_call:
    inputs:
      AZURE_SUBSCRIPTION:
        required: true
        type: string
      AZURE_RESOURCEGROUP:
        required: true
        type: string
      AZURE_WEBAPP_BASENAME:
        required: true
        type: string
      environment:
        required: true
        type: string      
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  DeployResources:
    name: Deploy Resources
    uses: ./.github/workflows/deployment/azure-deploy-resources.yml
    with:
      AZURE_SUBSCRIPTION: ${{ inputs.AZURE_SUBSCRIPTION }}
      AZURE_RESOURCEGROUP: ${{ inputs.AZURE_RESOURCEGROUP }}
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  DeployWebApp:
    name: Deploy WebApp
    uses: ./.github/workflows/deployment/azure-deploy-webapp.yml
    with:
      AZURE_WEBAPP_BASENAME: ${{ inputs.AZURE_WEBAPP_BASENAME }}
      environment: dev
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}