name: deploy webapp

on:
  workflow_call:
    inputs:
      AZURE_RESOURCEGROUP:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:    
  deploy_webapp_job:
    runs-on: ubuntu-latest    
    environment:
      name: github-${{ inputs.AZURE_RESOURCEGROUP }}-${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: webapp-${{ inputs.AZURE_RESOURCEGROUP }}-${{ inputs.environment }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: logout
      run: |
        az logout