name: deploy azure resources

on:
  workflow_call:
    inputs:
      AZURE_SUBSCRIPTION:
        required: true
        type: string
      AZURE_RESOURCEGROUP:
        required: true
        type: string        
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy_resources_job:
    environment: "github-${{ inputs.AZURE_RESOURCEGROUP }}-${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Bicep Deploy into "rg-${{ inputs.AZURE_RESOURCEGROUP }}"
      uses: azure/arm-deploy@v2
      id: deploy
      with:
        scope: resourcegroup
        subscriptionId: "sub-${{ inputs.AZURE_SUBSCRIPTION }}-${{ inputs.environment }}"
        resourceGroupName: "rg-${{ inputs.AZURE_RESOURCEGROUP }}"
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json environment=${{ inputs.environment }}
        failOnStdErr: true    
    - run: echo keyvaultName = {{ steps.deploy.outputs.keyVaultName }}
    - name: logout
      run: |
        az logout
        