name: CI + CD

permissions:
  id-token: write
  contents: read

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - closed

# env:
#     if: github.event_name == 'pull_request' 
#     environment: dev
    # if: github.event.pull_request.merged == true
    # environment: acc
    # github.event_name == 'pull_request' ? acc : github.event.pull_request.merged == true ? prd : dev

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      NODE_VERSION: '20.x'
      AZURE_WEBAPP_PACKAGE_PATH: 'dist/voetbaloog/browser'

#   DeployResourcesDev:
#     name: Deploy to Dev    
#     uses: ./.github/workflows/azure-deployment.yml
#     needs: [Build]    
#     with:
#       AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
#       AZURE_RESOURCEGROUP: ${{ vars.AZURE_RESOURCEGROUP }}
#       AZURE_WEBAPP_BASENAME: webapp-${{ vars.AZURE_RESOURCEGROUP }}-dev
#       environment: dev
#     secrets:
#       AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
#       AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  DeployResourcesDev:
    name: Deploy Resources Dev
    uses: ./.github/workflows/azure-deploy-resources.yml
    with:
      AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
      AZURE_RESOURCEGROUP: ${{ vars.AZURE_RESOURCEGROUP }}
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  DeployWebAppDev:
    needs: [Build,DeployResourcesDev]
    name: Deploy WebApp Dev
    uses: ./.github/workflows/azure-deploy-webapp.yml
    with:
      AZURE_WEBAPP_BASENAME: webapp-${{ vars.AZURE_RESOURCEGROUP }}
      environment: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  
#   DeployAcc:
#     name: Deploy to Acc 
#     if: github.event_name == 'pull_request' || github.event.pull_request.merged == true
#     needs: [DeployDev]
#     uses: ./.github/workflows/azure-deployment.yml
#     with:
#       AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
#       LOCATION: westeurope
#       environment: acc
#     secrets:
#       AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

#   DeployPrd:
#     name: Deploy to Prd
#     if: github.event.pull_request.merged == true
#     needs: [DeployAcc]
#     uses: ./.github/workflows/azure-deployment.yml
#     with:
#       AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }}
#       LOCATION: westeurope
#       environment: prd
#     secrets:
#       AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}   